name: Test Backend
on:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Docker Compose
        uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: '1.29.2'
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install yarn
        run: npm install --global yarn
      - name: Tests
        run: make default
      - name: Build docker image
        run: make docker-build-backend
      - name: Stop containers
        run: make stop-all