name: Test Backend
on:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Docker Compose
        uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: '1.29.2'
      - name: Prepare Backend
        run: make prepare-backend
      - name: Run yarn install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: --cwd backend install
      - name: Run yarn eslint
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: --cwd backend eslint
      - name: Run yarn unit-tests
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: --cwd backend unit-tests
      - name: Stop Containers
        run: make stop-all
