name: Test Backend
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Yarn install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: --cwd backend install
      - name: Test
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: --cwd backend test